# Generated by Django 5.2.7 on 2025-11-29 02:33

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalisisRiesgo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valor_riesgo', models.DecimalField(decimal_places=4, help_text='Valor de riesgo calculado (0-1)', max_digits=7, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('porcentaje_riesgo', models.DecimalField(decimal_places=2, help_text='Porcentaje de riesgo (0-100%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('nivel_riesgo', models.CharField(choices=[('muy_bajo', 'Muy Bajo'), ('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto'), ('muy_alto', 'Muy Alto')], help_text='Clasificación del nivel de riesgo', max_length=20)),
                ('fecha_calculo', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Análisis de Riesgo',
                'verbose_name_plural': 'Análisis de Riesgos',
                'ordering': ['-fecha_calculo'],
            },
        ),
        migrations.CreateModel(
            name='CalificacionOpcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(choices=[('ausente', 'Ausente'), ('deficiente', 'Deficiente'), ('vulnerable', 'Vulnerable'), ('adecuado', 'Adecuado'), ('eficaz', 'Eficaz')], max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('valor', models.DecimalField(decimal_places=3, max_digits=5)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Calificación Opción',
                'verbose_name_plural': 'Calificaciones Opciones',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='CategoriaSeguridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('icono', models.CharField(default='fas fa-shield-alt', max_length=50)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
                ('peso', models.DecimalField(decimal_places=2, default=1.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(5.0)])),
            ],
            options={
                'verbose_name': 'Categoría de Seguridad',
                'verbose_name_plural': 'Categorías de Seguridad',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='EscenarioRiesgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(choices=[('traspasando_cerramiento', 'Traspasando El Cerramiento Perimetral'), ('debilidad_procedimiento', 'Por Debilidad Del Procedimiento De Ingreso'), ('distraccion_vigilante', 'Distracción Al Vigilante'), ('simultaneamente_autorizada', 'Pasando Simultáneamente Con Una Persona Autorizada'), ('autorizacion_irresponsable', 'Autorización Irresponsable'), ('neutralizando_seguridad', 'Neutralizando Al Personal De Seguridad'), ('coaccionando_residente', 'Coaccionando A Residente O Persona Autorizada'), ('ingenieria_social', 'Por Ingeniería Social'), ('sobrepasando_controles', 'Sobrepasando Los Controles De Acceso'), ('suplantacion', 'Suplantación'), ('residente', 'Residente'), ('empleado_interno', 'Empleado Interno O Prestador De Servicios'), ('violando_puerta_principal', 'Violando La Seguridad De La Puerta Principal'), ('acceso_ventanas_balcones', 'Por Acceso Por Ventanas O Balcones'), ('ventosa_ruptura_paredes', 'Por ventosa o ruptura de paredes'), ('acceso_violento_persona', 'Por Acceso Violento A Persona Que Abre La Puerta'), ('suplantacion_residente', 'Por Suplantación Del Residente'), ('sometimiento_residente', 'Por Sometimiento Del Residente'), ('salida_violenta', 'Por Salida Violenta'), ('autorizacion_forzada', 'Por Autorización Forzada'), ('acceso_simplificado', 'Acceso Simplificado A Las Mismas'), ('salida_normal', 'Por Salida Normal'), ('autorizacion_suplantada', 'Por Autorización Suplantada'), ('accion_interna', 'Por Acción Interna'), ('permisividad_parqueos_asignados', 'Permisividad En El Uso De Parqueos Asignados'), ('permisividad_administracion_parqueaderos', 'Permisividad En La Administración De Pos Parqueaderos De Parte De Seguridad'), ('retiro_porterias', 'Retiro Por Porterías'), ('retiro_area_perimetral', 'Retiro Por El Área Perimetral'), ('salida_forzada_escoltas', 'Salida Forzada Suplantando A Escoltas'), ('salida_forzada_familiaridad', 'Salida Forzada Sometido Por Una Persona Que Le Obliga A Comportarse Con Familiaridad'), ('suplantando_servicios_medicos', 'Suplantando Servicios Médicos')], max_length=50)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Escenario de Riesgo',
                'verbose_name_plural': 'Escenarios de Riesgo',
                'ordering': ['tipo_riesgo', 'orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='MetricaCalidad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('confiabilidad', models.DecimalField(decimal_places=2, default=100.0, help_text='Porcentaje de confiabilidad del resultado', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('requiere_atencion', models.BooleanField(default=False, help_text='Indica si el resultado requiere atención especial')),
                ('tiempo_procesamiento_ms', models.PositiveIntegerField(blank=True, help_text='Tiempo de procesamiento en milisegundos', null=True)),
                ('ip_procesamiento', models.GenericIPAddressField(blank=True, null=True)),
                ('fecha_calculo', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Métrica de Calidad',
                'verbose_name_plural': 'Métricas de Calidad',
                'ordering': ['-fecha_calculo'],
            },
        ),
        migrations.CreateModel(
            name='PonderacionRiesgo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('peso_pregunta', models.DecimalField(decimal_places=3, default=1.0, help_text='Peso específico de la pregunta en la evaluación', max_digits=5, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(5.0)])),
                ('valor_ponderado', models.DecimalField(decimal_places=4, help_text='Valor final ponderado', max_digits=7, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('version_algoritmo', models.CharField(default='1.0', help_text='Versión del algoritmo de cálculo utilizado', max_length=10)),
                ('fecha_calculo', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ponderación de Riesgo',
                'verbose_name_plural': 'Ponderaciones de Riesgo',
                'ordering': ['-fecha_calculo'],
            },
        ),
        migrations.CreateModel(
            name='RecomendacionSistema',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_recomendacion', models.CharField(choices=[('accion_inmediata', 'Acción Inmediata'), ('prioridad_alta', 'Prioridad Alta'), ('monitoreo', 'Monitoreo'), ('mantenimiento', 'Mantenimiento'), ('optimo', 'Óptimo')], help_text='Tipo de recomendación basada en el nivel de riesgo', max_length=20)),
                ('recomendacion_automatica', models.TextField(help_text='Recomendación generada automáticamente por el sistema')),
                ('es_critica', models.BooleanField(default=False, help_text='Indica si la recomendación es crítica')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Recomendación del Sistema',
                'verbose_name_plural': 'Recomendaciones del Sistema',
                'ordering': ['-es_critica', '-fecha_generacion'],
            },
        ),
        migrations.CreateModel(
            name='TipoConjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('conjunto_cerrado', 'Conjunto Cerrado'), ('urbanizacion', 'Urbanización'), ('condominio', 'Condominio'), ('cluster', 'Cluster'), ('edificio', 'Edificio Residencial'), ('torres', 'Torres Residenciales')], max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('icono', models.CharField(default='fas fa-building', max_length=50)),
                ('color', models.CharField(default='#3498db', max_length=7)),
            ],
            options={
                'verbose_name': 'Tipo de Conjunto',
                'verbose_name_plural': 'Tipos de Conjuntos',
            },
        ),
        migrations.CreateModel(
            name='TipoRiesgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(choices=[('intrusion_general', 'Intrusión General'), ('conspiracion_intrusion', 'Conspiración Para Intrusión'), ('intrusion_unidad', 'Intrusión Unidad Residencial'), ('robo_vehiculos', 'Robo De Vehículos'), ('robo_bicicletas', 'Robo De Bicicletas'), ('dano_areas_comunes', 'Daño En Áreas Comunes'), ('conflictos_parqueos', 'Conflictos Por Mal Uso De Parqueos'), ('sustraccion_bienes', 'Sustracción De Bienes De Apartamentos'), ('secuestro', 'Secuestro')], max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Riesgo',
                'verbose_name_plural': 'Tipos de Riesgos',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Conjunto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nit', models.CharField(help_text='NIT del conjunto (Ej: 800123456-7)', max_length=15, unique=True, verbose_name='NIT')),
                ('nombre', models.CharField(max_length=200)),
                ('direccion', models.TextField()),
                ('ciudad', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=100)),
                ('numero_unidades', models.PositiveIntegerField(help_text='Número total de unidades residenciales', validators=[django.core.validators.MinValueValidator(1)])),
                ('numero_torres', models.PositiveIntegerField(default=1, help_text='Número de torres o bloques', validators=[django.core.validators.MinValueValidator(1)])),
                ('tiene_piscina', models.BooleanField(default=False)),
                ('tiene_gimnasio', models.BooleanField(default=False)),
                ('tiene_salon_social', models.BooleanField(default=False)),
                ('tiene_juegos_infantiles', models.BooleanField(default=False)),
                ('tiene_canchas_deportivas', models.BooleanField(default=False)),
                ('administrador_nombre', models.CharField(blank=True, max_length=200)),
                ('administrador_telefono', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Número de teléfono debe contener entre 9 y 20 caracteres (números, espacios, guiones, paréntesis permitidos).', regex='^\\+?[\\d\\s\\-\\(\\)]{9,20}$')])),
                ('administrador_email', models.EmailField(blank=True, max_length=254)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conjuntos', to=settings.AUTH_USER_MODEL)),
                ('tipo_conjunto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='risk_conjuntos.tipoconjunto')),
            ],
            options={
                'verbose_name': 'Conjunto Residencial',
                'verbose_name_plural': 'Conjuntos Residenciales',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='EvaluacionRiesgo',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Eliminado')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_evaluacion', models.CharField(choices=[('inicial', 'Evaluación Inicial'), ('periodica', 'Evaluación Periódica'), ('especial', 'Evaluación Especial'), ('auditoria', 'Auditoría')], default='periodica', max_length=20)),
                ('fecha_evaluacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('en_progreso', 'En Progreso'), ('completada', 'Completada'), ('revisada', 'Revisada')], default='borrador', max_length=20)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('promedio_general', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('observaciones_generales', models.TextField(blank=True, verbose_name='Observaciones Generales')),
                ('recomendaciones_generales', models.TextField(blank=True, verbose_name='Recomendaciones Generales')),
                ('conclusiones', models.TextField(blank=True, verbose_name='Conclusiones')),
                ('metodologia_aplicada', models.TextField(blank=True, verbose_name='Metodología Aplicada')),
                ('limitaciones_evaluacion', models.TextField(blank=True, verbose_name='Limitaciones de la Evaluación')),
                ('proximas_acciones', models.TextField(blank=True, verbose_name='Próximas Acciones Sugeridas')),
                ('ip_evaluacion', models.GenericIPAddressField(blank=True, null=True)),
                ('tiempo_evaluacion_minutos', models.PositiveIntegerField(blank=True, null=True)),
                ('conjunto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_riesgo', to='risk_conjuntos.conjunto')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluaciones_riesgo_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Evaluación de Riesgo',
                'verbose_name_plural': 'Evaluaciones de Riesgo',
                'ordering': ['-fecha_evaluacion'],
            },
        ),
        migrations.CreateModel(
            name='ArchivoEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_archivo', models.CharField(choices=[('evidencia', 'Evidencia Fotográfica'), ('documento', 'Documento de Soporte'), ('plano', 'Plano o Esquema'), ('informe', 'Informe Técnico'), ('certificado', 'Certificado'), ('acta', 'Acta de Reunión'), ('otro', 'Otro')], default='evidencia', max_length=20)),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('archivo', models.FileField(help_text='Formatos permitidos: PDF, DOC, DOCX, XLS, XLSX, JPG, JPEG, PNG, GIF (Máx. 10MB)', upload_to='evaluaciones/archivos/%Y/%m/%d/')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del archivo adjunto')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('tamaño_archivo', models.PositiveIntegerField(blank=True, help_text='Tamaño en bytes', null=True)),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos_adjuntos', to='risk_conjuntos.evaluacionriesgo')),
            ],
            options={
                'verbose_name': 'Archivo de Evaluación',
                'verbose_name_plural': 'Archivos de Evaluación',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='EvaluacionSeguridad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_evaluacion', models.CharField(choices=[('inicial', 'Evaluación Inicial'), ('periodica', 'Evaluación Periódica'), ('especial', 'Evaluación Especial'), ('auditoria', 'Auditoría')], default='periodica', max_length=20)),
                ('fecha_evaluacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('en_progreso', 'En Progreso'), ('completada', 'Completada'), ('revisada', 'Revisada')], default='borrador', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('score_total', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('observaciones', models.TextField(blank=True)),
                ('recomendaciones', models.TextField(blank=True)),
                ('ip_evaluacion', models.GenericIPAddressField(blank=True, null=True)),
                ('tiempo_evaluacion_minutos', models.PositiveIntegerField(blank=True, null=True)),
                ('conjunto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_seguridad', to='risk_conjuntos.conjunto')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluaciones_risk_conjuntos_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Evaluación de Seguridad',
                'verbose_name_plural': 'Evaluaciones de Seguridad',
                'ordering': ['-fecha_evaluacion'],
            },
        ),
        migrations.CreateModel(
            name='PreguntaEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_pregunta', models.TextField()),
                ('ayuda', models.TextField(blank=True, help_text='Texto de ayuda para la pregunta')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('obligatoria', models.BooleanField(default=True)),
                ('activa', models.BooleanField(default=True)),
                ('escenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='risk_conjuntos.escenarioriesgo')),
            ],
            options={
                'verbose_name': 'Pregunta de Evaluación',
                'verbose_name_plural': 'Preguntas de Evaluación',
                'ordering': ['escenario', 'orden', 'texto_pregunta'],
            },
        ),
        migrations.CreateModel(
            name='PreguntaSeguridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_pregunta', models.TextField()),
                ('ayuda', models.TextField(blank=True, help_text='Texto de ayuda para la pregunta')),
                ('tipo_respuesta', models.CharField(choices=[('rating', 'Calificación (1-5)'), ('booleana', 'Sí/No'), ('multiple', 'Opción Múltiple'), ('numerica', 'Numérica')], default='rating', max_length=20)),
                ('opciones_json', models.JSONField(blank=True, null=True)),
                ('obligatoria', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
                ('peso', models.DecimalField(decimal_places=2, default=1.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(3.0)])),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='risk_conjuntos.categoriaseguridad')),
            ],
            options={
                'verbose_name': 'Pregunta de Seguridad',
                'verbose_name_plural': 'Preguntas de Seguridad',
                'ordering': ['categoria', 'orden', 'texto_pregunta'],
            },
        ),
        migrations.CreateModel(
            name='RespuestaEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('respuesta_booleana', models.BooleanField(blank=True, null=True)),
                ('respuesta_multiple', models.CharField(blank=True, max_length=200)),
                ('respuesta_numerica', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('comentarios', models.TextField(blank=True)),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True)),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='risk_conjuntos.evaluacionseguridad')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risk_conjuntos.preguntaseguridad')),
            ],
            options={
                'verbose_name': 'Respuesta de Evaluación',
                'verbose_name_plural': 'Respuestas de Evaluación',
            },
        ),
        migrations.CreateModel(
            name='RespuestaPregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado_calculado', models.DecimalField(decimal_places=4, max_digits=7, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True)),
                ('calificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risk_conjuntos.calificacionopcion')),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='risk_conjuntos.evaluacionriesgo')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risk_conjuntos.preguntaevaluacion')),
            ],
            options={
                'verbose_name': 'Respuesta de Pregunta',
                'verbose_name_plural': 'Respuestas de Preguntas',
            },
        ),
        migrations.CreateModel(
            name='ResultadoEscenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promedio_escenario', models.DecimalField(decimal_places=4, max_digits=7, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('escenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risk_conjuntos.escenarioriesgo')),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_escenario', to='risk_conjuntos.evaluacionriesgo')),
            ],
            options={
                'verbose_name': 'Resultado por Escenario',
                'verbose_name_plural': 'Resultados por Escenario',
            },
        ),
        migrations.CreateModel(
            name='ResultadoPregunta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('calculado', 'Calculado'), ('validado', 'Validado'), ('revisado', 'Revisado'), ('aprobado', 'Aprobado')], default='calculado', max_length=20)),
                ('notas_evaluador', models.TextField(blank=True, help_text='Notas adicionales del evaluador')),
                ('fecha_calculo', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('analisis_riesgo', models.OneToOneField(blank=True, help_text='Análisis de riesgo asociado', null=True, on_delete=django.db.models.deletion.CASCADE, to='risk_conjuntos.analisisriesgo')),
                ('metrica_calidad', models.OneToOneField(blank=True, help_text='Métricas de calidad asociadas', null=True, on_delete=django.db.models.deletion.CASCADE, to='risk_conjuntos.metricacalidad')),
                ('ponderacion', models.OneToOneField(blank=True, help_text='Ponderación asociada', null=True, on_delete=django.db.models.deletion.CASCADE, to='risk_conjuntos.ponderacionriesgo')),
                ('recomendacion', models.OneToOneField(blank=True, help_text='Recomendación del sistema', null=True, on_delete=django.db.models.deletion.SET_NULL, to='risk_conjuntos.recomendacionsistema')),
                ('respuesta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resultado_procesado', to='risk_conjuntos.respuestapregunta')),
            ],
            options={
                'verbose_name': 'Resultado de Pregunta',
                'verbose_name_plural': 'Resultados de Preguntas',
                'ordering': ['-fecha_calculo'],
            },
        ),
        migrations.CreateModel(
            name='ScoreCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('numero_preguntas', models.PositiveIntegerField(default=0)),
                ('suma_puntuaciones', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risk_conjuntos.categoriaseguridad')),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores_categoria', to='risk_conjuntos.evaluacionseguridad')),
            ],
            options={
                'verbose_name': 'Score por Categoría',
                'verbose_name_plural': 'Scores por Categoría',
            },
        ),
        migrations.CreateModel(
            name='ResultadoRiesgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promedio_riesgo', models.DecimalField(decimal_places=4, max_digits=7, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_riesgo', to='risk_conjuntos.evaluacionriesgo')),
                ('tipo_riesgo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risk_conjuntos.tiporiesgo')),
            ],
            options={
                'verbose_name': 'Resultado por Riesgo',
                'verbose_name_plural': 'Resultados por Riesgo',
            },
        ),
        migrations.AddField(
            model_name='escenarioriesgo',
            name='tipo_riesgo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escenarios', to='risk_conjuntos.tiporiesgo'),
        ),
        migrations.CreateModel(
            name='ComentarioRiesgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(blank=True, help_text='Comentario general sobre la evaluación de este tipo de riesgo', verbose_name='Comentario General del Riesgo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_riesgo', to='risk_conjuntos.evaluacionriesgo')),
                ('tipo_riesgo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risk_conjuntos.tiporiesgo')),
            ],
            options={
                'verbose_name': 'Comentario de Riesgo',
                'verbose_name_plural': 'Comentarios de Riesgos',
                'ordering': ['tipo_riesgo__orden', 'tipo_riesgo__nombre'],
            },
        ),
        migrations.AddIndex(
            model_name='evaluacionriesgo',
            index=models.Index(fields=['conjunto', 'estado'], name='risk_conjun_conjunt_fd5db3_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluacionriesgo',
            index=models.Index(fields=['estado', 'fecha_evaluacion'], name='risk_conjun_estado_b6b7bc_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluacionriesgo',
            index=models.Index(fields=['creado_por'], name='risk_conjun_creado__78b7e6_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluacionriesgo',
            index=models.Index(fields=['deleted_at'], name='risk_conjun_deleted_4e3778_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='respuestaevaluacion',
            unique_together={('evaluacion', 'pregunta')},
        ),
        migrations.AlterUniqueTogether(
            name='respuestapregunta',
            unique_together={('evaluacion', 'pregunta')},
        ),
        migrations.AlterUniqueTogether(
            name='resultadoescenario',
            unique_together={('evaluacion', 'escenario')},
        ),
        migrations.AddIndex(
            model_name='resultadopregunta',
            index=models.Index(fields=['estado'], name='risk_conjun_estado_0125f0_idx'),
        ),
        migrations.AddIndex(
            model_name='resultadopregunta',
            index=models.Index(fields=['fecha_calculo'], name='risk_conjun_fecha_c_0ed76b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='scorecategoria',
            unique_together={('evaluacion', 'categoria')},
        ),
        migrations.AddIndex(
            model_name='conjunto',
            index=models.Index(fields=['propietario', 'activo'], name='risk_conjun_propiet_4cd396_idx'),
        ),
        migrations.AddIndex(
            model_name='conjunto',
            index=models.Index(fields=['ciudad'], name='risk_conjun_ciudad_3e1e5a_idx'),
        ),
        migrations.AddIndex(
            model_name='conjunto',
            index=models.Index(fields=['fecha_creacion'], name='risk_conjun_fecha_c_8663af_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='resultadoriesgo',
            unique_together={('evaluacion', 'tipo_riesgo')},
        ),
        migrations.AlterUniqueTogether(
            name='escenarioriesgo',
            unique_together={('tipo_riesgo', 'codigo')},
        ),
        migrations.AlterUniqueTogether(
            name='comentarioriesgo',
            unique_together={('evaluacion', 'tipo_riesgo')},
        ),
    ]
