# Generated by Django 5.2.7 on 2025-11-29 02:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArbolDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Árbol')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Árbol de Decisión',
                'verbose_name_plural': 'Árboles de Decisión',
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_dane', models.CharField(max_length=2, unique=True, verbose_name='Código DANE')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Departamento')),
                ('region', models.CharField(blank=True, choices=[('andina', 'Región Andina'), ('caribe', 'Región Caribe'), ('pacifica', 'Región Pacífica'), ('orinoquia', 'Región Orinoquía'), ('amazonia', 'Región Amazonía'), ('insular', 'Región Insular')], max_length=50, verbose_name='Región Geográfica')),
                ('nivel_riesgo', models.CharField(choices=[('muy_bajo', 'Muy Bajo'), ('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto'), ('muy_alto', 'Muy Alto'), ('critico', 'Crítico')], default='medio', max_length=20, verbose_name='Nivel de Riesgo de la Zona')),
                ('factor_riesgo', models.DecimalField(decimal_places=3, default=0.5, help_text='Valor numérico del riesgo para cálculos de evaluación', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Factor de Riesgo (0.000 - 1.000)')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones sobre el Nivel de Riesgo')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ZonaRiesgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la Zona')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('nivel_riesgo_base', models.DecimalField(decimal_places=3, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Nivel de Riesgo Base')),
                ('coordenadas', models.TextField(blank=True, help_text='Coordenadas en formato JSON')),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Zona de Riesgo',
                'verbose_name_plural': 'Zonas de Riesgo',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PerfilSeguridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('PA', 'Pasaporte'), ('TI', 'Tarjeta de Identidad')], default='CC', max_length=2, verbose_name='Tipo de Documento')),
                ('numero_documento', models.CharField(max_length=20, unique=True, verbose_name='Número de Documento')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro'), ('NR', 'Prefiero no responder')], max_length=2, verbose_name='Género')),
                ('telefono_principal', models.CharField(max_length=20, verbose_name='Teléfono Principal')),
                ('telefono_emergencia', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono de Emergencia')),
                ('cargo_politico', models.CharField(choices=[('alcalde', 'Alcalde/Alcaldesa'), ('concejal', 'Concejal'), ('diputado', 'Diputado/Diputada'), ('senador', 'Senador/Senadora'), ('gobernador', 'Gobernador/Gobernadora'), ('ministro', 'Ministro/Ministra'), ('candidato', 'Candidato/Candidata'), ('lider_social', 'Líder Social'), ('activista', 'Activista Político'), ('funcionario', 'Funcionario Público'), ('otro', 'Otro')], max_length=20, verbose_name='Cargo Político')),
                ('partido_politico', models.CharField(blank=True, max_length=100, null=True, verbose_name='Partido Político')),
                ('nivel_exposicion', models.CharField(choices=[('muy_alta', 'Muy Alta'), ('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=10, verbose_name='Nivel de Exposición Pública')),
                ('departamento', models.CharField(max_length=50, verbose_name='Departamento')),
                ('municipio', models.CharField(max_length=50, verbose_name='Municipio')),
                ('direccion_residencia', models.TextField(verbose_name='Dirección de Residencia')),
                ('direccion_trabajo', models.TextField(blank=True, null=True, verbose_name='Dirección de Trabajo')),
                ('tiene_esquema_seguridad', models.BooleanField(default=False, verbose_name='¿Tiene Esquema de Seguridad?')),
                ('nivel_esquema_seguridad', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nivel del Esquema de Seguridad')),
                ('amenazas_recibidas', models.BooleanField(default=False, verbose_name='¿Ha Recibido Amenazas?')),
                ('fecha_ultima_amenaza', models.DateField(blank=True, null=True, verbose_name='Fecha de Última Amenaza')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones Adicionales')),
                ('contacto_emergencia_nombre', models.CharField(max_length=100, verbose_name='Nombre Contacto de Emergencia')),
                ('contacto_emergencia_telefono', models.CharField(max_length=20, verbose_name='Teléfono Contacto de Emergencia')),
                ('contacto_emergencia_relacion', models.CharField(max_length=50, verbose_name='Relación Contacto de Emergencia')),
                ('estado_perfil', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('suspendido', 'Suspendido'), ('archivado', 'Archivado')], default='activo', max_length=10, verbose_name='Estado del Perfil')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, help_text='Usuario que creó este perfil de seguridad', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perfiles_seguridad', to=settings.AUTH_USER_MODEL, verbose_name='Propietario')),
            ],
            options={
                'verbose_name': 'Perfil de Seguridad',
                'verbose_name_plural': 'Perfiles de Seguridad',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='EvaluacionSeguridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('iniciada', 'Iniciada'), ('en_progreso', 'En Progreso'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='iniciada', max_length=20)),
                ('evaluador_nombre', models.CharField(blank=True, help_text='Nombre de la persona que realizó la evaluación (opcional)', max_length=200, null=True, verbose_name='Nombre del Evaluador')),
                ('probabilidad_total', models.DecimalField(decimal_places=3, default=0, max_digits=6, verbose_name='Probabilidad Total de Riesgo')),
                ('factor_geografico', models.DecimalField(decimal_places=3, default=0, help_text='Riesgo adicional basado en ubicación de residencia y desplazamientos', max_digits=6, verbose_name='Factor de Riesgo Geográfico')),
                ('probabilidad_con_geografia', models.DecimalField(decimal_places=3, default=0, max_digits=6, verbose_name='Probabilidad Total con Factor Geográfico')),
                ('municipios_desplazamiento_json', models.JSONField(default=list, help_text='Lista de municipios donde se desplaza con frecuencia y motivo', verbose_name='Municipios de Desplazamiento')),
                ('incluir_municipio_residencia', models.BooleanField(default=True, help_text='Si se debe considerar el municipio de residencia del perfil en el cálculo', verbose_name='Incluir Municipio de Residencia')),
                ('nivel_riesgo', models.CharField(blank=True, choices=[('muy_bajo', 'Muy Bajo'), ('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto'), ('muy_alto', 'Muy Alto')], max_length=20, null=True)),
                ('respuestas_json', models.JSONField(default=dict, verbose_name='Respuestas en JSON')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('completada_en', models.DateTimeField(blank=True, null=True)),
                ('arbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='security_probabilistic.arboldecision')),
                ('created_by', models.ForeignKey(blank=True, help_text='Usuario que realizó esta evaluación de seguridad', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_security_probabilistic_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('perfil', models.ForeignKey(help_text='Cada evaluación debe estar asociada a un perfil de seguridad verificado', on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='security_probabilistic.perfilseguridad', verbose_name='Perfil de Seguridad Asociado')),
            ],
            options={
                'verbose_name': 'Evaluación de Seguridad',
                'verbose_name_plural': 'Evaluaciones de Seguridad',
                'ordering': ['-creada_en'],
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Texto de la Pregunta')),
                ('orden', models.PositiveIntegerField(verbose_name='Orden')),
                ('valor', models.DecimalField(decimal_places=3, default=0.0, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor/Peso de la Pregunta')),
                ('var_amenaza', models.CharField(blank=True, help_text='Capacidad, Intencionalidad, Exposición, Inductor, Interés, Valuabilidad', max_length=100, verbose_name='Variable de Amenaza')),
                ('es_pregunta_inicial', models.BooleanField(default=False, verbose_name='Es Pregunta Inicial')),
                ('arbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='security_probabilistic.arboldecision')),
                ('pregunta_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preguntas_hijas', to='security_probabilistic.pregunta', verbose_name='Pregunta Padre')),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
                'ordering': ['arbol', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='OpcionRespuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=500, verbose_name='Texto de la Opción')),
                ('valor_ponderado', models.DecimalField(decimal_places=3, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor Ponderado')),
                ('orden', models.PositiveIntegerField(verbose_name='Orden')),
                ('es_respuesta_final', models.BooleanField(default=False, verbose_name='Es Respuesta Final')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='security_probabilistic.pregunta')),
                ('pregunta_siguiente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opciones_que_llevan_aqui', to='security_probabilistic.pregunta', verbose_name='Pregunta Siguiente')),
            ],
            options={
                'verbose_name': 'Opción de Respuesta',
                'verbose_name_plural': 'Opciones de Respuesta',
                'ordering': ['pregunta', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_dane', models.CharField(max_length=5, unique=True, verbose_name='Código DANE')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Municipio')),
                ('categoria', models.CharField(blank=True, choices=[('especial', 'Categoría Especial'), ('primera', 'Primera Categoría'), ('segunda', 'Segunda Categoría'), ('tercera', 'Tercera Categoría'), ('cuarta', 'Cuarta Categoría'), ('quinta', 'Quinta Categoría'), ('sexta', 'Sexta Categoría')], max_length=20, verbose_name='Categoría Municipal')),
                ('nivel_riesgo', models.CharField(choices=[('muy_bajo', 'Muy Bajo'), ('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto'), ('muy_alto', 'Muy Alto'), ('critico', 'Crítico')], default='medio', max_length=20, verbose_name='Nivel de Riesgo de la Zona')),
                ('factor_riesgo', models.DecimalField(decimal_places=3, default=0.5, help_text='Valor numérico del riesgo para cálculos de evaluación', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Factor de Riesgo (0.000 - 1.000)')),
                ('usa_riesgo_departamento', models.BooleanField(default=True, help_text='Si está marcado, usará el nivel de riesgo del departamento. Si no, usará el propio.', verbose_name='Usar Riesgo del Departamento')),
                ('poblacion', models.PositiveIntegerField(blank=True, null=True, verbose_name='Población Estimada')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones sobre el Nivel de Riesgo')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipios', to='security_probabilistic.departamento', verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
                'ordering': ['departamento__nombre', 'nombre'],
                'unique_together': {('departamento', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='RespuestaEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_aplicado', models.DecimalField(decimal_places=3, max_digits=6)),
                ('orden_respuesta', models.PositiveIntegerField(verbose_name='Orden de Respuesta')),
                ('respondida_en', models.DateTimeField(auto_now_add=True)),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='security_probabilistic.evaluacionseguridad')),
                ('opcion_seleccionada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='security_probabilistic.opcionrespuesta')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='security_probabilistic.pregunta')),
            ],
            options={
                'verbose_name': 'Respuesta de Evaluación',
                'verbose_name_plural': 'Respuestas de Evaluación',
                'ordering': ['evaluacion', 'orden_respuesta'],
                'unique_together': {('evaluacion', 'pregunta')},
            },
        ),
    ]
