# Generated by Django 5.2.7 on 2025-11-29 02:41

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionGoal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('goal_type', models.CharField(choices=[('page_visit', 'Page Visit'), ('form_submit', 'Form Submit'), ('button_click', 'Button Click'), ('time_spent', 'Time Spent')], max_length=50)),
                ('target_url', models.URLField(blank=True, null=True)),
                ('target_element', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'conversion_goal',
            },
        ),
        migrations.CreateModel(
            name='RiskCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('weight', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(10.0)], verbose_name='Peso/Importancia')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Categoría de Riesgo',
                'verbose_name_plural': 'Categorías de Riesgo',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SecurityCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('gestion_organizacion', 'Gestión y Organización de la Seguridad'), ('seguridad_externa', 'Seguridad Externa'), ('seguridad_perimetral', 'Seguridad Perimetral'), ('seguridad_internas', 'Seguridad en Áreas Internas'), ('controles_accesos', 'Controles de Accesos al Hotel'), ('seguridad_habitaciones', 'Seguridad en Habitaciones'), ('seguridad_activos', 'Seguridad de Activos Críticos del Hotel'), ('seguridad_parqueo', 'Seguridad en Áreas de Parqueo'), ('gestion_humana', 'Seguridad en el Proceso de Gestión Humana'), ('seguridad_eventos', 'Seguridad en Eventos'), ('seguridad_ayb', 'Seguridad en A&B'), ('seguridad_reservas', 'Seguridad en Reservas'), ('seguridad_compras', 'Seguridad en el Proceso de Compras'), ('gestion_emergencias', 'Seguridad y Gestión de Emergencias')], max_length=30, unique=True, verbose_name='Código de Categoría')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('icon', models.CharField(default='fas fa-shield-alt', max_length=50, verbose_name='Ícono')),
                ('weight', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(5.0)], verbose_name='Peso en el Análisis')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Categoría de Seguridad',
                'verbose_name_plural': 'Categorías de Seguridad',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(max_length=255)),
                ('event_type', models.CharField(max_length=100)),
                ('event_data', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_event',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('report_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('custom', 'Custom')], max_length=50)),
                ('date_from', models.DateTimeField()),
                ('date_to', models.DateTimeField()),
                ('data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_report',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del Hotel')),
                ('address', models.TextField(verbose_name='Dirección')),
                ('city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('country', models.CharField(max_length=100, verbose_name='País')),
                ('category', models.CharField(choices=[('1_star', '1 Estrella'), ('2_star', '2 Estrellas'), ('3_star', '3 Estrellas'), ('4_star', '4 Estrellas'), ('5_star', '5 Estrellas'), ('luxury', 'Lujo')], max_length=20, verbose_name='Categoría')),
                ('total_rooms', models.PositiveIntegerField(verbose_name='Total de Habitaciones')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, verbose_name='Sitio Web')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_hotels', to=settings.AUTH_USER_MODEL, verbose_name='Propietario')),
            ],
            options={
                'verbose_name': 'Hotel',
                'verbose_name_plural': 'Hoteles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SecurityAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assessment_type', models.CharField(choices=[('inicial', 'Análisis Inicial'), ('periodico', 'Análisis Periódico'), ('especial', 'Análisis Especial'), ('auditoria', 'Auditoría de Riesgo')], max_length=20, verbose_name='Tipo de Evaluación')),
                ('assessment_date', models.DateTimeField(verbose_name='Fecha de Evaluación')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('status', models.CharField(choices=[('in_progress', 'En Progreso'), ('completed', 'Completado'), ('reviewed', 'Revisado')], default='in_progress', max_length=20, verbose_name='Estado')),
                ('overall_score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Puntuación General')),
                ('risk_level', models.CharField(blank=True, choices=[('muy_bajo', 'Muy Bajo'), ('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto'), ('muy_alto', 'Muy Alto')], max_length=20, null=True, verbose_name='Nivel de Riesgo General')),
                ('observations', models.TextField(blank=True, verbose_name='Observaciones Generales')),
                ('recommendations', models.TextField(blank=True, verbose_name='Recomendaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Finalización')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_assessments', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_assessments', to='risk_hoteles.hotel', verbose_name='Hotel')),
                ('selected_categories', models.ManyToManyField(to='risk_hoteles.securitycategory', verbose_name='Categorías Seleccionadas')),
            ],
            options={
                'verbose_name': 'Evaluación de Seguridad',
                'verbose_name_plural': 'Evaluaciones de Seguridad',
                'ordering': ['-assessment_date'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='evaluaciones/evidencias/%Y/%m/', verbose_name='Imagen de Evidencia')),
                ('original_name', models.CharField(max_length=255, verbose_name='Nombre Original del Archivo')),
                ('file_size', models.PositiveIntegerField(verbose_name='Tamaño del Archivo (bytes)')),
                ('content_type', models.CharField(max_length=50, verbose_name='Tipo de Contenido')),
                ('description', models.TextField(blank=True, verbose_name='Descripción de la Evidencia')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Subida')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_images', to='risk_hoteles.securityassessment', verbose_name='Evaluación')),
            ],
            options={
                'verbose_name': 'Evidencia de Evaluación',
                'verbose_name_plural': 'Evidencias de Evaluación',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='SecurityQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='Texto de la Pregunta')),
                ('help_text', models.TextField(blank=True, verbose_name='Texto de Ayuda')),
                ('is_required', models.BooleanField(default=True, verbose_name='Obligatoria')),
                ('weight', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(3.0)], verbose_name='Peso de la Pregunta')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='risk_hoteles.securitycategory', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Pregunta de Seguridad',
                'verbose_name_plural': 'Preguntas de Seguridad',
                'ordering': ['category', 'order'],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(max_length=255, unique=True)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('pages_visited', models.IntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_session',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page_url', models.URLField()),
                ('page_title', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('time_on_page', models.IntegerField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risk_hoteles.usersession')),
            ],
            options={
                'db_table': 'page_view',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Conversion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risk_hoteles.conversiongoal')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risk_hoteles.usersession')),
            ],
            options={
                'db_table': 'conversion',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ClickEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('element_id', models.CharField(blank=True, max_length=255, null=True)),
                ('element_class', models.CharField(blank=True, max_length=255, null=True)),
                ('element_text', models.TextField(blank=True, null=True)),
                ('page_url', models.URLField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('coordinates_x', models.IntegerField(blank=True, null=True)),
                ('coordinates_y', models.IntegerField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risk_hoteles.usersession')),
            ],
            options={
                'db_table': 'click_event',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SecurityCategoryComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(blank=True, help_text='Observaciones generales, evidencias, recomendaciones sobre esta categoría', verbose_name='Comentarios Generales')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_comments', to='risk_hoteles.securityassessment', verbose_name='Evaluación')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risk_hoteles.securitycategory', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Comentario de Categoría',
                'verbose_name_plural': 'Comentarios de Categorías',
                'unique_together': {('assessment', 'category')},
            },
        ),
        migrations.CreateModel(
            name='SecurityCategoryScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_sum', models.IntegerField(default=0, verbose_name='Suma de Calificaciones')),
                ('question_count', models.IntegerField(default=0, verbose_name='Cantidad de Preguntas Válidas')),
                ('average_score', models.FloatField(default=0.0, verbose_name='Promedio de Calificaciones')),
                ('percentage', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Porcentaje Final')),
                ('calculated_at', models.DateTimeField(auto_now=True, verbose_name='Calculado en')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_scores', to='risk_hoteles.securityassessment', verbose_name='Evaluación')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risk_hoteles.securitycategory', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Puntaje de Categoría',
                'verbose_name_plural': 'Puntajes de Categorías',
                'unique_together': {('assessment', 'category')},
            },
        ),
        migrations.CreateModel(
            name='SecurityResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(blank=True, choices=[(0, 'Expuesto - Se carece de dicho control'), (1, 'Vulnerable - Control totalmente vulnerable'), (2, 'Insuficiente - Control funciona ocasionalmente'), (3, 'Estándar - Control funciona regularmente'), (4, 'Adecuado - Control funciona adecuadamente'), (5, 'Excelente - Control con nivel superior')], null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Calificación')),
                ('not_applicable', models.BooleanField(default=False, verbose_name='No Aplica')),
                ('comments', models.TextField(blank=True, verbose_name='Comentarios')),
                ('evidence', models.TextField(blank=True, verbose_name='Evidencia/Justificación')),
                ('answered_at', models.DateTimeField(auto_now=True, verbose_name='Respondido en')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='risk_hoteles.securityassessment', verbose_name='Evaluación')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risk_hoteles.securityquestion', verbose_name='Pregunta')),
            ],
            options={
                'verbose_name': 'Respuesta de Seguridad',
                'verbose_name_plural': 'Respuestas de Seguridad',
                'unique_together': {('assessment', 'question')},
            },
        ),
    ]
