# Generated by Django 6.0.4 on 2026-04-21 21:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_hoteles', '0002_hotel_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Valor numérico')),
                ('label', models.CharField(max_length=100, verbose_name='Etiqueta corta')),
                ('description', models.TextField(verbose_name='Descripción completa')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Opción de Respuesta',
                'verbose_name_plural': 'Opciones de Respuesta',
                'ordering': ['order', 'value'],
            },
        ),
    ]
