# Generated by Django 6.0.4 on 2026-04-21 21:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_hoteles', '0003_add_response_option_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responseoption',
            name='value',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(10)], verbose_name='Valor numérico'),
        ),
    ]
