# Generated by Django 4.2.25 on 2025-10-18 03:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(blank=True, max_length=40, verbose_name='Clave de sesión')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expira')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Carrito',
                'verbose_name_plural': 'Carritos',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre interno')),
                ('display_name', models.CharField(max_length=200, verbose_name='Nombre a mostrar')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('icon', models.CharField(blank=True, help_text='Clase CSS del icono', max_length=50, verbose_name='Icono')),
                ('color', models.CharField(default='#007bff', help_text='Color hexadecimal', max_length=7, verbose_name='Color')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Módulo',
                'verbose_name_plural': 'Módulos',
                'ordering': ['order', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Número de orden')),
                ('billing_name', models.CharField(max_length=200, verbose_name='Nombre facturación')),
                ('billing_email', models.EmailField(max_length=254, verbose_name='Email facturación')),
                ('billing_phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('billing_address', models.TextField(blank=True, verbose_name='Dirección')),
                ('billing_city', models.CharField(blank=True, max_length=100, verbose_name='Ciudad')),
                ('billing_country', models.CharField(default='Colombia', max_length=100, verbose_name='País')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Subtotal')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Impuestos')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total')),
                ('currency', models.CharField(default='COP', max_length=3, verbose_name='Moneda')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('paid', 'Pagado'), ('failed', 'Fallido'), ('cancelled', 'Cancelado'), ('refunded', 'Reembolsado')], default='pending', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadatos')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Orden',
                'verbose_name_plural': 'Órdenes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlanType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Tipo de Plan',
                'verbose_name_plural': 'Tipos de Planes',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WompiTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('wompi_transaction_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='ID Transacción Wompi')),
                ('wompi_reference', models.CharField(blank=True, max_length=100, verbose_name='Referencia Wompi')),
                ('wompi_status', models.CharField(choices=[('PENDING', 'Pendiente'), ('APPROVED', 'Aprobado'), ('DECLINED', 'Rechazado'), ('VOIDED', 'Anulado'), ('ERROR', 'Error')], default='PENDING', max_length=20, verbose_name='Estado Wompi')),
                ('amount_in_cents', models.PositiveIntegerField(verbose_name='Monto en centavos')),
                ('currency', models.CharField(default='COP', max_length=3, verbose_name='Moneda')),
                ('payment_method', models.CharField(blank=True, max_length=50, verbose_name='Método de pago')),
                ('payment_source_id', models.CharField(blank=True, max_length=100, verbose_name='ID Fuente de pago')),
                ('redirect_url', models.URLField(blank=True, verbose_name='URL redirección')),
                ('wompi_response', models.JSONField(blank=True, default=dict, verbose_name='Respuesta Wompi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Procesado')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wompi_transactions', to='subscriptions.order')),
            ],
            options={
                'verbose_name': 'Transacción Wompi',
                'verbose_name_plural': 'Transacciones Wompi',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=50, verbose_name='Tipo de evento')),
                ('wompi_event_id', models.CharField(max_length=100, unique=True, verbose_name='ID Evento Wompi')),
                ('payload', models.JSONField(default=dict, verbose_name='Payload completo')),
                ('processed', models.BooleanField(default=False, verbose_name='Procesado')),
                ('processing_error', models.TextField(blank=True, verbose_name='Error procesamiento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Procesado')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.wompitransaction')),
            ],
            options={
                'verbose_name': 'Evento Webhook',
                'verbose_name_plural': 'Eventos Webhook',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('monthly_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio mensual')),
                ('quarterly_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio trimestral')),
                ('yearly_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio anual')),
                ('trial_days', models.PositiveIntegerField(default=14, verbose_name='Días de prueba')),
                ('max_users', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Máximo usuarios')),
                ('max_reports', models.IntegerField(default=10, help_text='-1 para ilimitado', verbose_name='Máximo reportes/mes')),
                ('max_storage_gb', models.IntegerField(default=1, verbose_name='Almacenamiento GB')),
                ('features', models.JSONField(blank=True, default=dict, verbose_name='Características')),
                ('limits', models.JSONField(blank=True, default=dict, verbose_name='Límites específicos')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destacado')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='subscriptions.module')),
                ('plan_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='subscriptions.plantype')),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Planes',
                'ordering': ['module', 'order', 'monthly_price'],
                'unique_together': {('module', 'plan_type')},
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=200, verbose_name='Nombre del plan')),
                ('billing_cycle', models.CharField(max_length=20, verbose_name='Ciclo facturación')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio unitario')),
                ('features_snapshot', models.JSONField(blank=True, default=dict, verbose_name='Características')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='subscriptions.order')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.plan')),
            ],
            options={
                'verbose_name': 'Item de Orden',
                'verbose_name_plural': 'Items de Orden',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Mensual'), ('quarterly', 'Trimestral'), ('yearly', 'Anual')], max_length=20, verbose_name='Ciclo facturación')),
                ('start_date', models.DateTimeField(verbose_name='Fecha inicio')),
                ('end_date', models.DateTimeField(verbose_name='Fecha fin')),
                ('next_billing_date', models.DateTimeField(blank=True, null=True, verbose_name='Próxima facturación')),
                ('status', models.CharField(choices=[('active', 'Activa'), ('cancelled', 'Cancelada'), ('expired', 'Expirada'), ('suspended', 'Suspendida')], default='active', max_length=20, verbose_name='Estado')),
                ('is_trial', models.BooleanField(default=False, verbose_name='Es período de prueba')),
                ('trial_end_date', models.DateTimeField(blank=True, null=True, verbose_name='Fin período prueba')),
                ('current_users', models.PositiveIntegerField(default=0, verbose_name='Usuarios actuales')),
                ('current_reports', models.PositiveIntegerField(default=0, verbose_name='Reportes este período')),
                ('current_storage_gb', models.FloatField(default=0.0, verbose_name='Almacenamiento usado GB')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='subscriptions.order')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='subscriptions.plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Suscripción',
                'verbose_name_plural': 'Suscripciones',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'plan')},
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Mensual'), ('quarterly', 'Trimestral'), ('yearly', 'Anual')], default='monthly', max_length=20, verbose_name='Ciclo de facturación')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio unitario')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='subscriptions.cart')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.plan')),
            ],
            options={
                'verbose_name': 'Item del Carrito',
                'verbose_name_plural': 'Items del Carrito',
                'unique_together': {('cart', 'plan', 'billing_cycle')},
            },
        ),
    ]
