# Generated by Django 4.2.24 on 2025-11-11 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_auto_20251019_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Descuentos'),
        ),
        migrations.AddField(
            model_name='cart',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Si el carrito está activo para modificaciones', verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='cart',
            name='is_completed',
            field=models.BooleanField(default=False, help_text='Si la compra fue completada', verbose_name='Completado'),
        ),
        migrations.AddField(
            model_name='cart',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Impuestos'),
        ),
        migrations.AddField(
            model_name='cart',
            name='tax_rate',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5, verbose_name='Tasa de impuesto'),
        ),
    ]
