# Generated by Django 4.2.24 on 2025-11-11 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_cart_discount_amount_cart_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='tax_amount',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='tax_rate',
        ),
    ]
