# Generated by Django 6.0.4 on 2026-04-21 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_remove_cart_discount_amount_remove_cart_tax_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='billing_cycle',
            field=models.CharField(choices=[('monthly', 'Mensual'), ('quarterly', 'Trimestral'), ('yearly', 'Anual')], default='yearly', max_length=20, verbose_name='Ciclo de facturación'),
        ),
    ]
