# Generated by Django 4.2.24 on 2025-10-17 17:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text='Cuéntanos un poco sobre ti (máximo 500 caracteres)', max_length=500, verbose_name='Biografía'),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=50, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.CharField(blank=True, max_length=100, verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, max_length=50, verbose_name='País'),
        ),
        migrations.AddField(
            model_name='user',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Imagen de portada para tu perfil.', null=True, upload_to='covers/%Y/%m/', verbose_name='Imagen de portada'),
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, max_length=100, verbose_name='Departamento'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_notifications',
            field=models.BooleanField(default=True, help_text='Recibir notificaciones importantes por correo electrónico', verbose_name='Notificaciones por email'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False, verbose_name='Email verificado'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro'), ('N', 'Prefiero no decir')], max_length=1, null=True, verbose_name='Género'),
        ),
        migrations.AddField(
            model_name='user',
            name='job_title',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cargo/Puesto'),
        ),
        migrations.AddField(
            model_name='user',
            name='linkedin',
            field=models.URLField(blank=True, verbose_name='LinkedIn'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_verified',
            field=models.BooleanField(default=False, verbose_name='Teléfono verificado'),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(choices=[('es', 'Español'), ('en', 'English'), ('fr', 'Français')], default='es', max_length=2, verbose_name='Idioma preferido'),
        ),
        migrations.AddField(
            model_name='user',
            name='sms_notifications',
            field=models.BooleanField(default=False, help_text='Recibir notificaciones por mensaje de texto', verbose_name='Notificaciones por SMS'),
        ),
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(blank=True, default='America/Mexico_City', max_length=50, verbose_name='Zona horaria'),
        ),
        migrations.AddField(
            model_name='user',
            name='twitter',
            field=models.CharField(blank=True, help_text='Solo el nombre de usuario, sin @', max_length=50, verbose_name='Twitter'),
        ),
        migrations.AddField(
            model_name='user',
            name='two_factor_enabled',
            field=models.BooleanField(default=False, verbose_name='2FA habilitado'),
        ),
        migrations.AddField(
            model_name='user',
            name='website',
            field=models.URLField(blank=True, verbose_name='Sitio web'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Sube una imagen de perfil. Se redimensionará automáticamente.', null=True, upload_to='avatars/%Y/%m/', verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='Formato: +52123456789', max_length=17, validators=[django.core.validators.RegexValidator(message="El número de teléfono debe estar en formato: '+999999999'. Hasta 15 dígitos permitidos.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Teléfono'),
        ),
    ]
