# Generated by Django 4.2.25 on 2025-10-17 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_bio_user_city_user_company_user_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('login_success', 'Login exitoso'), ('login_failure', 'Login fallido'), ('password_change', 'Cambio de contraseña'), ('password_reset', 'Reset de contraseña'), ('account_lockout', 'Bloqueo de cuenta'), ('account_unlock', 'Desbloqueo de cuenta'), ('2fa_enabled', '2FA habilitado'), ('2fa_disabled', '2FA deshabilitado'), ('2fa_backup_used', 'Código de backup 2FA usado'), ('suspicious_activity', 'Actividad sospechosa'), ('data_export', 'Exportación de datos'), ('profile_update', 'Actualización de perfil')], max_length=50, verbose_name='Tipo de evento')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadatos adicionales')),
                ('severity', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('critical', 'Crítica')], default='medium', max_length=20, verbose_name='Severidad')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento de Seguridad',
                'verbose_name_plural': 'Eventos de Seguridad',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='users_secur_user_id_3afb96_idx'), models.Index(fields=['event_type', 'timestamp'], name='users_secur_event_t_6eca38_idx'), models.Index(fields=['severity', 'timestamp'], name='users_secur_severit_ac0552_idx'), models.Index(fields=['ip_address', 'timestamp'], name='users_secur_ip_addr_fd7e35_idx')],
            },
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=254, verbose_name='Username/Email')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('success', models.BooleanField(default=False, verbose_name='Exitoso')),
                ('failure_reason', models.CharField(blank=True, max_length=200, verbose_name='Razón del fallo')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Intento de Login',
                'verbose_name_plural': 'Intentos de Login',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['username', 'timestamp'], name='users_login_usernam_9b9158_idx'), models.Index(fields=['ip_address', 'timestamp'], name='users_login_ip_addr_7c2b9b_idx'), models.Index(fields=['success', 'timestamp'], name='users_login_success_d3b092_idx')],
            },
        ),
        migrations.CreateModel(
            name='AccountLockout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('reason', models.CharField(choices=[('failed_attempts', 'Intentos fallidos consecutivos'), ('suspicious_activity', 'Actividad sospechosa'), ('admin_manual', 'Bloqueo manual por administrador'), ('security_breach', 'Posible violación de seguridad')], default='failed_attempts', max_length=50, verbose_name='Razón del bloqueo')),
                ('locked_at', models.DateTimeField(auto_now_add=True, verbose_name='Bloqueado en')),
                ('unlock_at', models.DateTimeField(verbose_name='Desbloquear en')),
                ('unlocked_at', models.DateTimeField(blank=True, null=True, verbose_name='Desbloqueado en')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('failed_attempts_count', models.PositiveIntegerField(default=0, verbose_name='Número de intentos fallidos')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('unlocked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unlocked_accounts', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lockouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bloqueo de Cuenta',
                'verbose_name_plural': 'Bloqueos de Cuenta',
                'ordering': ['-locked_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='users_accou_user_id_494dd1_idx'), models.Index(fields=['unlock_at', 'is_active'], name='users_accou_unlock__ddb89d_idx'), models.Index(fields=['ip_address', 'locked_at'], name='users_accou_ip_addr_d3ccd3_idx')],
            },
        ),
    ]
