# Generated by Django 4.2.25 on 2025-10-30 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_securityevent_loginattempt_accountlockout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='timezone',
            field=models.CharField(blank=True, default='America/Bogota', max_length=50, verbose_name='Zona horaria'),
        ),
    ]
