# Generated by Django 4.2.24 on 2025-11-11 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_timezone'),
    ]

    operations = [
    ]
