# Generated by Django 5.2.7 on 2025-11-11 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_user_preferred_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cover_image',
        ),
    ]
