# Generated by Django 5.2.7 on 2025-11-12 02:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evaluador', models.CharField(choices=[('evaluator', 'Evaluador'), ('reviewer', 'Revisor'), ('analyst', 'Analista'), ('administrator', 'Administrador')], default='evaluator', max_length=20, verbose_name='Tipo de Evaluador')),
                ('estado', models.CharField(choices=[('pending', 'Pendiente'), ('active', 'Activo'), ('suspended', 'Suspendido'), ('inactive', 'Inactivo')], default='pending', max_length=20, verbose_name='Estado')),
                ('modulos_permitidos', models.JSONField(blank=True, default=list, help_text='Lista de módulos a los que tiene acceso este evaluador', verbose_name='Módulos Permitidos')),
                ('permisos_especiales', models.JSONField(blank=True, default=dict, help_text='Configuración específica de permisos por módulo', verbose_name='Permisos Especiales')),
                ('max_evaluaciones_mes', models.PositiveIntegerField(default=10, help_text='Número máximo de evaluaciones que puede realizar por mes', verbose_name='Máximo Evaluaciones por Mes')),
                ('puede_crear_reportes', models.BooleanField(default=True, help_text='Si puede generar reportes de evaluación', verbose_name='Puede Crear Reportes')),
                ('puede_editar_evaluaciones', models.BooleanField(default=True, help_text='Si puede editar evaluaciones existentes', verbose_name='Puede Editar Evaluaciones')),
                ('acceso_completo_dashboard', models.BooleanField(default=False, help_text='Si tiene acceso completo al dashboard del usuario principal', verbose_name='Acceso Completo Dashboard')),
                ('notas', models.TextField(blank=True, help_text='Notas adicionales sobre este evaluador', verbose_name='Notas')),
                ('fecha_invitacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Invitación')),
                ('fecha_activacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Activación')),
                ('fecha_ultimo_acceso', models.DateTimeField(blank=True, null=True, verbose_name='Último Acceso')),
                ('fecha_expiracion', models.DateTimeField(blank=True, help_text='Fecha hasta la cual el evaluador tiene acceso', null=True, verbose_name='Fecha de Expiración')),
                ('is_active', models.BooleanField(default=True, help_text='Si este evaluador está activo en el sistema', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('usuario_evaluador', models.ForeignKey(help_text='Usuario que actuará como evaluador', on_delete=django.db.models.deletion.CASCADE, related_name='evaluador_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Evaluador')),
                ('usuario_principal', models.ForeignKey(help_text='Usuario principal que administra este evaluador', on_delete=django.db.models.deletion.CASCADE, related_name='evaluadores_administrados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Principal')),
            ],
            options={
                'verbose_name': 'Evaluador',
                'verbose_name_plural': 'Evaluadores',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvitacionEvaluador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_invitado', models.EmailField(help_text='Email de la persona que será invitada como evaluador', max_length=254, verbose_name='Email del Invitado')),
                ('nombre_invitado', models.CharField(blank=True, help_text='Nombre opcional del invitado', max_length=100, verbose_name='Nombre del Invitado')),
                ('mensaje_personal', models.TextField(blank=True, help_text='Mensaje personalizado para la invitación', verbose_name='Mensaje Personal')),
                ('tipo_evaluador_propuesto', models.CharField(choices=[('evaluator', 'Evaluador'), ('reviewer', 'Revisor'), ('analyst', 'Analista'), ('administrator', 'Administrador')], default='evaluator', max_length=20, verbose_name='Tipo de Evaluador Propuesto')),
                ('modulos_propuestos', models.JSONField(blank=True, default=list, help_text='Módulos a los que tendría acceso', verbose_name='Módulos Propuestos')),
                ('token_invitacion', models.CharField(help_text='Token único para la invitación', max_length=100, unique=True, verbose_name='Token de Invitación')),
                ('estado', models.CharField(choices=[('pending', 'Pendiente'), ('accepted', 'Aceptada'), ('declined', 'Rechazada'), ('expired', 'Expirada'), ('cancelled', 'Cancelada')], default='pending', max_length=20, verbose_name='Estado')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Envío')),
                ('fecha_expiracion', models.DateTimeField(help_text='Fecha hasta la cual es válida la invitación', verbose_name='Fecha de Expiración')),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Respuesta')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('evaluador_creado', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitacion_origen', to='evaluadores.evaluador', verbose_name='Evaluador Creado')),
                ('usuario_principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitaciones_enviadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Principal')),
            ],
            options={
                'verbose_name': 'Invitación de Evaluador',
                'verbose_name_plural': 'Invitaciones de Evaluadores',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='evaluador',
            index=models.Index(fields=['usuario_principal', 'estado'], name='evaluadores_usuario_d18f14_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluador',
            index=models.Index(fields=['usuario_evaluador', 'is_active'], name='evaluadores_usuario_45596a_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluador',
            index=models.Index(fields=['estado', 'is_active'], name='evaluadores_estado_0f914f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='evaluador',
            unique_together={('usuario_principal', 'usuario_evaluador')},
        ),
        migrations.AddIndex(
            model_name='invitacionevaluador',
            index=models.Index(fields=['token_invitacion'], name='evaluadores_token_i_e7a851_idx'),
        ),
        migrations.AddIndex(
            model_name='invitacionevaluador',
            index=models.Index(fields=['email_invitado', 'estado'], name='evaluadores_email_i_a24662_idx'),
        ),
        migrations.AddIndex(
            model_name='invitacionevaluador',
            index=models.Index(fields=['usuario_principal', 'estado'], name='evaluadores_usuario_8461b9_idx'),
        ),
    ]
