# Generated by Django 5.2.7 on 2025-11-12 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluadores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluador',
            name='apellidos',
            field=models.CharField(default='Sin especificar', help_text='Apellidos del evaluador', max_length=100, verbose_name='Apellidos'),
        ),
        migrations.AddField(
            model_name='evaluador',
            name='nombres',
            field=models.CharField(default='Sin especificar', help_text='Nombres del evaluador', max_length=100, verbose_name='Nombres'),
        ),
    ]
