# Generated by Django 5.2.7 on 2025-11-12 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluadores', '0002_evaluador_apellidos_evaluador_nombres'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluador',
            name='permisos_crud',
            field=models.JSONField(blank=True, default=dict, help_text='Permisos específicos CRUD para cada módulo. Formato: {"modulo": {"create": bool, "read": bool, "update": bool, "delete": bool, "export": bool, "approve": bool}}', verbose_name='Permisos CRUD por Módulo'),
        ),
        migrations.AlterField(
            model_name='evaluador',
            name='permisos_especiales',
            field=models.JSONField(blank=True, default=dict, help_text='Configuración específica de permisos por módulo (legacy)', verbose_name='Permisos Especiales'),
        ),
    ]
