# Generated by Django 5.2.7 on 2025-11-12 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluadores', '0003_evaluador_permisos_crud_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitacionevaluador',
            name='acceso_completo_dashboard_propuesto',
            field=models.BooleanField(default=False, verbose_name='Acceso Completo Dashboard (Propuesto)'),
        ),
        migrations.AddField(
            model_name='invitacionevaluador',
            name='apellidos_propuestos',
            field=models.CharField(blank=True, help_text='Apellidos para el evaluador', max_length=100, verbose_name='Apellidos Propuestos'),
        ),
        migrations.AddField(
            model_name='invitacionevaluador',
            name='fecha_expiracion_propuesta',
            field=models.DateTimeField(blank=True, help_text='Fecha de expiración propuesta para el evaluador', null=True, verbose_name='Fecha Expiración Propuesta'),
        ),
        migrations.AddField(
            model_name='invitacionevaluador',
            name='max_evaluaciones_mes_propuesto',
            field=models.PositiveIntegerField(default=50, help_text='Límite de evaluaciones por mes propuesto', verbose_name='Máx. Evaluaciones/Mes Propuesto'),
        ),
        migrations.AddField(
            model_name='invitacionevaluador',
            name='nombres_propuestos',
            field=models.CharField(blank=True, help_text='Nombres para el evaluador', max_length=100, verbose_name='Nombres Propuestos'),
        ),
        migrations.AddField(
            model_name='invitacionevaluador',
            name='notas_propuestas',
            field=models.TextField(blank=True, help_text='Notas propuestas para el evaluador', verbose_name='Notas Propuestas'),
        ),
        migrations.AddField(
            model_name='invitacionevaluador',
            name='permisos_crud_propuestos',
            field=models.JSONField(blank=True, default=dict, help_text='Permisos CRUD específicos propuestos', verbose_name='Permisos CRUD Propuestos'),
        ),
        migrations.AddField(
            model_name='invitacionevaluador',
            name='puede_crear_reportes_propuesto',
            field=models.BooleanField(default=False, verbose_name='Puede Crear Reportes (Propuesto)'),
        ),
        migrations.AddField(
            model_name='invitacionevaluador',
            name='puede_editar_evaluaciones_propuesto',
            field=models.BooleanField(default=False, verbose_name='Puede Editar Evaluaciones (Propuesto)'),
        ),
    ]
