# Generated by Django 4.2.24 on 2025-11-18 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluadores', '0004_invitacionevaluador_acceso_completo_dashboard_propuesto_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InvitacionEvaluador',
        ),
    ]
