# Generated by Django 5.2.7 on 2025-11-19 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluadores', '0005_remove_invitacion_evaluador'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluatorActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('evaluation_started', 'Evaluación Iniciada'), ('evaluation_completed', 'Evaluación Completada'), ('evaluation_updated', 'Evaluación Actualizada'), ('comment_added', 'Comentario Agregado'), ('report_generated', 'Reporte Generado'), ('login', 'Inicio de Sesión'), ('logout', 'Cierre de Sesión')], max_length=50, verbose_name='Acción')),
                ('description', models.CharField(help_text='Descripción detallada de la actividad', max_length=255, verbose_name='Descripción')),
                ('module', models.CharField(help_text='Módulo donde se realizó la actividad', max_length=50, verbose_name='Módulo')),
                ('status', models.CharField(choices=[('completed', 'Completado'), ('in_progress', 'En Progreso'), ('pending', 'Pendiente'), ('cancelled', 'Cancelado'), ('error', 'Error')], default='completed', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Información adicional sobre la actividad', verbose_name='Metadatos')),
                ('evaluador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='evaluadores.evaluador')),
            ],
            options={
                'verbose_name': 'Actividad de Evaluador',
                'verbose_name_plural': 'Actividades de Evaluadores',
                'ordering': ['-created_at'],
            },
        ),
    ]
